targets = [ "//:test" ]

[[dependency]]
package = "github.com/buckaroo-pm/boost-algorithm"
version = "branch=master"

[[dependency]]
package = "github.com/buckaroo-pm/boost-detail"
version = "branch=master"

[[dependency]]
package = "github.com/buckaroo-pm/boost-function"
version = "branch=master"

[[dependency]]
package = "github.com/buckaroo-pm/boost-iterator"
version = "branch=master"

[[dependency]]
package = "github.com/buckaroo-pm/boost-mpl"
version = "branch=master"

[[dependency]]
package = "github.com/buckaroo-pm/boost-numeric_conversion"
version = "branch=master"

[[dependency]]
package = "github.com/buckaroo-pm/boost-preprocessor"
version = "branch=master"

[[dependency]]
package = "github.com/buckaroo-pm/boost-smart_ptr"
version = "branch=master"

[[dependency]]
package = "github.com/buckaroo-pm/boost-timer"
version = "branch=master"

[[dependency]]
package = "github.com/buckaroo-pm/boost-type_index"
version = "branch=master"
